DNA = 'TCCGGGTTTAGAAGCGTTTGTTGAAGCGACTCCAAAGATCGATCTCCCGCGATTCTGTTAAATTATATTGCTATTCTGAAAACTACAGTAATTAGGGCAGGCAGCTGGCTGTAGTACACCCGGGGCTATTGCAATCTGCGAATCTCACGTTAGAGGGATGCGGCCAGTCCTGCGATTGTTGCCTACCAAATCTACTACCGCCTTCACAACTCGAAATTGCCTTCTCATCGCTATTTCGGCCACTGCGCTAAATGAATGGTATCAAACCCCCAACGTCTATAGTTTAGACGCCACTAGGGTTTCATATAAGCCCGTGAGCTCCGGATAACCTCACTCCGAACCTAGACTCCTGCCCCCAGTGCCATTTCAGCGAGTCAGGCGTGTACGGTCCCAACCGGACGTCTAACTAGTTTTCCATGGACTCTGTTGCCTTCTACAGGCATGGTTGCGTGTACATGAATCTGTTCCACTAGTGTTGGGACTATTTACCTAGCTGCTCTTCCGCTTACTAGATACGCGTATAGGTCGTAATGCATCGTTAAGGACAGCCTAAGCCAATAATACATTAATAACAGTCTTAGGCCTATGGATGGGGTTCAGTAAAATTTATGCCGGCAGTAAGGCCATTTCTGGCGGTGACTATGCAGCCTTGGAATTCGTCCTGCAAGGTCAGTTGATTTTGTGGCGAAATAACCGTGGACATTGCATCCTATACGACTTTTCGGTCCGGAACATAAGCAAAGTAGAGTTCATCTTACTCAATTAACAGTAATGGGTTACTACTTGCCGCTGTGAGATCTAATAGTTATAT'

contadorNucleotideos = {}


for nucleotideo in DNA.strip():
    if nucleotideo not in contadorNucleotideos:
        contadorNucleotideos[nucleotideo] = 1
    else:contadorNucleotideos[nucleotideo] += 1

"""
#Contando mostando o nucleotideo ao lado do número
for nucleo_temp, valor in contadorNucleotideos.items():
    print(nucleo_temp+ ' ' + str(valor))
"""

#Contado ordenando os nucleotídeos
#print(sorted(contadorNucleotideos.items()))
for nucleo_temp, valor in sorted(contadorNucleotideos.items()):
    print(valor, end=' ')